### Macro file for "Original.cc"
### @author Tsuguo Aramaki
### @date 2015 March 23

#/run/verbose 1
#/run/particle/applyCuts
#/event/verbose 0
#/tracking/verbose 0
#/tracking/storeTrajectory 1

# set active sensitive detector
#/hits/inactivate DetectorSD

/process/em/deexcitation World true true true
/process/list

/Visualization 0
/CheckOverlap 1
/OutputFormat 0
/TrackType 0
/TrackEdep 1

/OutputDirectory output

/GeneralParticleSource 1
/gps/particle anti_deuteron
/gps/ene/type Gauss
/gps/ene/mono 260.0 MeV
/gps/ene/min 20.0 MeV
/gps/ene/max 500.0 MeV
/gps/ene/sigma 500.0 MeV
/gps/pos/type Point
/gps/pos/centre 0.0 0.0 2200.0 cm
/gps/direction 0.0 0.0 -1.0
/gps/ang/type focused

/OutputFile test_deuteron
#/update
/run/beamOn 500